os: "linux"
arch: "amd64"

kube_vip_version: "v0.8.0"
vip_interface: ens3
vip: 192.168.4.10

metallb_version: v0.13.12
lb_range: 192.168.4.20-192.168.4.30
lb_pool_name: first-pool

rke2_version: "v1.29.4+rke2r1"
rke2_install_dir: "/usr/local/bin"
rke2_binary_url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-amd64"

ansible_user: stackops
ansible_port: 234
ansible_ssh_private_key_file: /home/stackops/.ssh/id_rsa
ansible_become: true
ansible_become_method: sudo
